pipeline {
    agent  {
        label 'roboshop-dev'
    }
    environment { 
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '108717859359'
        PROJECT = 'roboshop'
        COMPONENT = 'catalogue'
        
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
      /*   disableConcurrentBuilds()
        ansiColor('xterm') */
    }
  /*   parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    } */
    // Build
    stages {
         stage('init') {
            steps {
                script {
                    withAWS(credentials: 'jenkins-ecr-user', region: 'us-east-1') {
                        sh """
                        cd 0-vpc
                        terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script {
                    withAWS(credentials : 'jenkins-ecr-user', region: 'us-east-1') {
                        sh """
                        cd 0-vpc
                        terraform plan
                        """
                    }
                }
            }
        }

        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps {
                script {
                    withAWS(credentials: 'jenkins-ecr-user', region: 'us-east-1') {
                        sh """
                        cd 0-vpc
                        terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        // Down stream jobs
       stage('Trigger SG') {
            steps {
                script {
                    build job: '02-sg', 
                      propagate: false,  // even SG fails VPC will not be effected
                      wait: false // VPC will not wait for SG pipeline completion
                }
            }
        }
        
        
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}