pipeline {
    agent {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '108717859359'
        PROJECT = 'roboshop'
        COMPONENT = 'catalogue'
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('Init') {
            steps {
                script {
                    withAWS(credentials: 'jenkins-ecr-user', region: "${REGION}") {
                        sh """
                        set -e
                        cd 09-frontend-alb
                        rm -rf .terraform .terraform.lock.hcl
                        terraform init -reconfigure -upgrade
                        terraform validate
                        """
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    withAWS(credentials: 'jenkins-ecr-user', region: "${REGION}") {
                        sh """
                        set -e
                        cd 09-frontend-alb
                        terraform plan -out=tfplan
                        """
                    }
                }
            }
        }

        stage('Apply') {
            steps {
                lock(resource: 'terraform-frontend-alb') {
                    script {
                        withAWS(credentials: 'jenkins-ecr-user', region: "${REGION}") {
                            sh """
                            set -e
                            cd 09-frontend-alb
                            terraform apply -auto-approve tfplan
                            """
                        }
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'Cleaning workspace...'
            deleteDir()
        }
        success { 
            echo '✅ Terraform Apply Success'
        }
        failure { 
            echo '❌ Terraform Apply Failed'
        }
    }
}
