pipeline {
    agent {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '108717859359'
        PROJECT = 'roboshop'
        COMPONENT = 'catalogue'
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    
    stages {
        stage('init') {
            steps {
                ansiColor('xterm') {
                    script {
                        withAWS(credentials: 'jenkins-ecr-user', region: 'us-east-1') {
                            sh """
                                cd 02-sg
                                terraform init -reconfigure
                            """
                        }
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                ansiColor('xterm') {
                    script {
                        withAWS(credentials: 'jenkins-ecr-user', region: 'us-east-1') {
                            sh """
                                cd 02-sg
                                terraform plan
                            """
                        }
                    }
                }
            }
        }

        stage('Apply') {
            steps {
                ansiColor('xterm') {
                    script {
                        withAWS(credentials: 'jenkins-ecr-user', region: 'us-east-1') {
                            sh """
                                cd 02-sg
                                terraform apply -auto-approve
                            """
                        }
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}
